### PR TITLE
Force playerbots locale enUS and Fix multi-language DBC loading

### PR DESCRIPTION
**Pull request by AlvinZhu**
首先，感谢你对playerbot做的修复，我试了下，主要功能已经可用了。
这是我几个月前提到过的关于DBC的问题我的具体修复方案。可以避免服务端使用英文DBC，导致中文客户端汉化不完整的问题。
Playerbots使用英文DBC,以确保其能够正常施放技能。
同时修复服务端，可以正常加载多种不同语言的DBC。
这样修改之后，客户端可以正常使用非英文语言，同时playerbot技能施放正常。

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/liyunfan1223/mod-playerbots/issues/29

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. add enUS and zhCN DBC files to Server‘s dbc folder.
2. start Server.
3. connect to the Server with zhCN Client.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by liyunfan1223** [comment]
我测试下来没有问题，可以解决之前的问题，感谢你提交的更新！

**Comment by oiuv** [comment]
> 我测试下来没有问题，可以解决之前的问题，感谢你提交的更新！

怎么测试，我直接把服务端换用中文客户端生成的dbc不行呀，具体要怎么配置？

**Comment by liyunfan1223** [comment]
> > 我测试下来没有问题，可以解决之前的问题，感谢你提交的更新！
> 
> 怎么测试，我直接把服务端换用中文客户端生成的dbc不行呀，具体要怎么配置？

我的方法是
1. 在原来的 dbc 文件夹里建一个名为 zhCN 的文件夹，把中文提取的所有 .dbc 文件放在 zhCN 里
2. 修改worldserver.conf，设置DBC.Locale = 4

**Comment by oiuv** [comment]
> > > 我测试下来没有问题，可以解决之前的问题，感谢你提交的更新！
> > 
> > 
> > 怎么测试，我直接把服务端换用中文客户端生成的dbc不行呀，具体要怎么配置？
> 
> 我的方法是
> 
> 1. 在原来的 dbc 文件夹里建一个名为 zhCN 的文件夹，把中文提取的所有 .dbc 文件放在 zhCN 里
> 2. 修改worldserver.conf，设置DBC.Locale = 4

原来如此，不过我看不出用中文DBC和英文DBC的区别，好像显示什么是和客户关有关的，服务端影响了哪里没看出来。

**Comment by lene42287** [comment]
我测试下来 这么做并不成功啊，bot不放技能

**Comment by oiuv** [comment]
> 我测试下来 这么做并不成功啊，bot不放技能

我测试是可以的，简单的说就是把中文dbc目录复制到默认的Dbc目录中，并改目录中的这个Dbc为名zhCN，目录结构如下：

```
├─data
│  ├─Cameras
│  ├─dbc
│  │  └─zhCN
│  ├─maps
│  ├─mmaps
│  └─vmaps
```
启动后会显示多个DBC可用：
image

**Pull request merged**
